config/routes.rb
Rails.application.routes.draw do

  
  resources :comments
  resources :ingredients
  resources :recipes
  devise_for :users
  
  
  get 'recipes/index' => 'recipes#index'

  get 'recipes/about' => 'recipes#about'

  get 'recipes/contact' => 'recipes#contact'
  
  get 'index' => 'recipes#index'

  get 'about' => 'recipes#about'

  get 'contact' => 'recipes#contact'
  
  root 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :user
    has_many :ingredients
    has_many :comments
    
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :rating, :instructions, :user_id)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.select :rating, ["1","2","3","4","5"], {:include_blank => 'Rating'}, class: "form-control" %>
  </div>
   

  <div class="field">
    <%= f.label :instructions %><br>
  
    <!--changed by mike on friday after 8pm-->
    <%= f.text_area :instructions, class: "form-control", placeholder: "Type instructions for the recipe here, please", rows: 20 %>
   </div>
   
  
  <!--this sticks the user id of whoever is creating the recipe into the recipe -->
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
    
  </div>
   
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'View this Recipe', @recipe %> |
<%= link_to 'All Recipes', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Recipes</h1>
<p>
<%= link_to  new_recipe_path do %>
     <span class="glyphicon glyphicon-plus"></span> Add New Recipe
<% end %>
</p>

<div class="row">
  <% @recipes.each do |recipe| %>
   <div class="col-md-6">
      <div class="well"> 
      <h2><%= link_to recipe.title, recipe %></h2>
       <p>
           <!--this is the code that does the ratings, and sets the icon to a fork, and makes the fork yellow in color-->
        <% "#{recipe.rating}".to_i.times do %>
         <!--<span class="glyphicon glyphicon-star"></span>-->
         <span><i class="ionicons ion-fork yellow"></i></span>
        <% end %>
                <!--end of rating related code-->
       </p>
      
        <div class="panel-body">
           
            <p><%= recipe.instructions[0..250] %>...[ <%= link_to "READ MORE", recipe %> ]

            <p><strong><%=recipe.updated_at.strftime('%d %B %Y %H:%M:%S') %></strong></p>
          </div>
      
      Created by chef: <%= recipe.user.email %>
      
      <h4><%= link_to edit_recipe_path(recipe) do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          
          <%= link_to recipe, method: :delete, data: { confirm: 'Are you sure?' } do %>
             <span class="glyphicon glyphicon-trash"></span>
          <% end %>
          </h4> 
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'All Recipes', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>

  
        <!--this is the code that does the ratings, and sets the icon to a fork, and makes the fork yellow in color-->
        <% "#{@recipe.rating}".to_i.times do %>
         <!--<span class="glyphicon glyphicon-star"></span>-->
         <span><i class="ionicons ion-fork yellow"></i></span>
        <% end %>
        <!--end of rating related code-->
  
  
</p>

<p>
  <strong>Instructions:</strong>
  <pre><%= @recipe.instructions %></pre>
</p>

<%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %> |
<%= link_to 'All Recipes', recipes_path %>