config/routes.rb
Rails.application.routes.draw do

  
  resources :comments
  resources :ingredients
  resources :recipes
  devise_for :users
  
  
  get 'recipes/index' => 'recipes#index'

  get 'recipes/about' => 'recipes#about'

  get 'recipes/contact' => 'recipes#contact'
  
  get 'index' => 'recipes#index'

  get 'about' => 'recipes#about'

  get 'contact' => 'recipes#contact'
  
  root 'recipes#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
   belongs_to :recipe
   
   
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @recipe = Recipe.new
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    @recipe = Recipe.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredientname, :recipe_id_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@ingredient) do |f| %>
      <% if @ingredient.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

          <ul>
          <% @ingredient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :ingredientname, class: "sr-only" %>
        <%= f.text_field :ingredientname, class: "form-control", placeholder: "Ingredient Name" %>
      </div>

      <div class="form-group">
  
              <!--I don't get this.  I am literally telling it the value is the number 2, and yet it does not get saved.  wtf?  -->
              <%= f.label :recipe_id %>
              <%= f.label :recipe_id,  value = 2 %>
              <!--ideally this would be a select and would offer a drop down menu of all the various recipes that have been added already. -->
         <br>
       </div>

      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Ingredients</h1>
<p><%= link_to new_ingredient_path do %>
  <span class="glyphicon glyphicon-plus"></span> Add New Ingredient
  <% end %>
</p>

  <div class="row">
    <% @ingredients.each do |ingredient| %>
      <div class="col-md-6">
        <div class="well">
          <h2><%= link_to ingredient.ingredientname, ingredient %></h2>
          

          <h4><%= link_to edit_ingredient_path(ingredient) do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>   | 
          <%= link_to ingredient, method: :delete, data: { confirm: 'Are you sure?' } do %>
             <span class="glyphicon glyphicon-trash"></span>
          <% end %>
          </h4>   
          
        </div>
      </div>
    <% end %>
  </div>

<br>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredientname:</strong>
  <%= @ingredient.ingredientname %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredient.recipe.title %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>